# Generated by Django 4.1.3 on 2022-12-14 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_docter', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='parkinsonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDVP_Fo_Hz', models.FloatField()),
                ('MDVP_Fhi_Hz', models.FloatField()),
                ('MDVP_Flo_Hz', models.FloatField()),
                ('MDVP_Jitter', models.FloatField()),
                ('MDVP_Jitter_Abs', models.FloatField()),
                ('MDVP_RAP', models.FloatField()),
                ('MDVP_PPQ', models.FloatField()),
                ('Jitter_DDP', models.FloatField()),
                ('MDVP_Shimmer', models.FloatField()),
                ('MDVP_Shimmer_dB', models.FloatField()),
                ('Shimmer_APQ3', models.FloatField()),
                ('Shimmer_APQ5', models.FloatField()),
                ('MDVP_APQ', models.FloatField()),
                ('Shimmer_DDA', models.FloatField()),
                ('NHR', models.FloatField()),
                ('HNR', models.FloatField()),
                ('RPDE', models.FloatField()),
                ('DFA', models.FloatField()),
                ('spread1', models.FloatField()),
                ('spread2', models.FloatField()),
                ('D2', models.FloatField()),
                ('PPE', models.FloatField()),
                ('result', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='heartTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.FloatField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=15)),
                ('cp', models.FloatField()),
                ('trestbps', models.FloatField()),
                ('chol', models.FloatField()),
                ('fbs', models.FloatField()),
                ('restecg', models.FloatField()),
                ('thalach', models.FloatField()),
                ('exang', models.FloatField()),
                ('oldpeak', models.FloatField()),
                ('slope', models.FloatField()),
                ('ca', models.FloatField()),
                ('thal', models.FloatField()),
                ('result', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='diabtesTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.FloatField()),
                ('glucose', models.FloatField()),
                ('bloodpressure', models.FloatField()),
                ('skinthickness', models.FloatField()),
                ('insulin', models.FloatField()),
                ('bmi', models.FloatField()),
                ('dpf', models.FloatField()),
                ('age', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chestTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('file', models.ImageField(upload_to='chest_photos')),
                ('resultChest', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('glucouse', models.FloatField()),
                ('insuline', models.FloatField()),
                ('homa', models.FloatField()),
                ('leptin', models.FloatField()),
                ('adiponcetin', models.FloatField()),
                ('resistiin', models.FloatField()),
                ('mcp', models.FloatField()),
                ('result', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='alzhimarTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=15)),
                ('Age', models.FloatField()),
                ('EDUC', models.FloatField()),
                ('SES', models.FloatField()),
                ('MMSE', models.FloatField()),
                ('eTIV', models.FloatField()),
                ('nWBV', models.FloatField()),
                ('ASF', models.FloatField()),
                ('result', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
