# Generated by Django 4.1.3 on 2022-12-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0002_post_delete_chesttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resultChest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
