# Generated by Django 4.1.3 on 2023-01-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0005_alter_post_resultpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_docter',
            field=models.BooleanField(),
        ),
    ]
