# Generated by Django 4.1.3 on 2023-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0006_alter_account_is_docter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_docter',
            field=models.BooleanField(default=False),
        ),
    ]
